### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by noxify** [noxify/gridsome-plugin-remark-embed#28]
The current documentation exists only in the README, not sure if it makes sense to use a external source (built with Gridsome ;) ) or using the github wiki to handle all the configurations and to keep it easy to read and maintain when there are more providers available...

**Comment by RehanSaeed** [comment]
One thing that might be worth documenting is the best way to import the external scripts. If the plugin can do that for me, even better.

**Comment by noxify** [comment]
I have reactivated one of my old domains.
Moved the documentation to: https://webstone.info/documentation/gridsome-plugin-remark-embed

Now each provider has it's own section/page.

I hope it's now easier to find the information about the external assets embeding.

@RehanSaeed - You can set the `omitscript` property to `false` to use the script embed from the 3rd party provider. But then, it's possible that a script will be loaded multiple times.
