### ISSUE TITLE
Remove margin: 0 from YouTube template

### ISSUE THREAD

**Issue by missmatsuko** [noxify/gridsome-plugin-remark-embed#29]
**Is your feature request related to a problem? Please describe.**
I've added margin styles to direct children of a rich text area (where the markdown gets generated) so that there's an equal amount of space between elements, but the YouTube embed has inline margin styles that can't be disabled.

Is there a reason why top/bottom margin needs to be set at all?

**Describe the solution you'd like**
Change [template](https://github.com/noxify/gridsome-plugin-remark-embed/blob/master/src/templates/Youtube.hbs) to use margin-left and margin-right styles instead of using the margin shorthand which also sets margin-top and margin-bottom to 0.

**Describe alternatives you've considered**
I could make my own template, but that seems overkill for such a small change. I don't want to add !important styles, either.

**Comment by noxify** [comment]
Hi,

Thanks for submitting the issue :)

The HTML is the default from YouTube - not sure if deleting the `margin` has some impact e.g. centering the video.

Maybe we could update the margin option where the user has the possibility to define all margins not only the second one.

Would this solve your problem?

**Comment by noxify** [comment]
Damn. I should read the description correctly :D your described solution is fine for me - I will update template and the options tomorrow.

Thanks!

**Comment by noxify** [comment]
Hi @missmatsuko,

i have added a new option `margin` to the Youtube configuration.
Keep it empty to use the default definition via `align`.
( sets `0 auto` or whatever you have defined as align value )

Alternative you can set `margin: false` to disable the margin inside the template.
Or set `margin: 0px 2px 3px 4px` (or whatever you need as margin) to define top, bottom, left, right.

Hope this solves your problem.

FYI: Currently, the changes are tested only with a gridsome 0.6.9 setup.
I hope I can find tomorrow more time to update all my plugins (thanks god, i have only two :D ) to the latest gridsome version.

If there are any questions or something is not working as expected, feel free to reopen the issue or create a new one :)

Thanks & regards
Marcus

**Comment by missmatsuko** [comment]
Great, thank you! Will 1.1.5 be up on npm soon?

**Comment by noxify** [comment]
@missmatsuko Thanks for the reminder - latest version is now available.
And thanks for the PR <3
