### ISSUE TITLE
Invalid margin on YouTube embed when using align keywords

### ISSUE THREAD

**Issue by missmatsuko** [noxify/gridsome-plugin-remark-embed#31]
**Describe the bug**
The `align` parameter for the YouTube configuration accepts `left` and `right`, and puts them in the embed's margin style like: `margin: 0 left;` or `margin: 0 right;`. 

`left` and `right` are not valid values for `margin`, so the style is actually broken/not applied.

**To Reproduce**
1. Use the YouTube embed, and set align to `left` or `right`.
2. Check the embed's value for `margin` on the front end.

**Expected behavior**
Using documented values should not produce invalid CSS.

I guess either:
1. `left` and `right` should not be accepted/documented values for `align`. This seems to follow the original plugin, [Gridsome Remark YouTube Plugin](https://github.com/rylandg/gridsome-plugin-remark-youtube), which only documents values of `0` and `auto` (both valid values for margin).
2. When `left` is passed, margin should be `margin: 0 auto 0 0;`. When `right` is passed, margin should be `margin: 0 0 0 auto;`.
3. Deprecate the `align` parameter altogether since the `margin` parameter controls the same thing but with more control. Maybe `align` and `margin` could both be deprecated, actually? The other embeds don't have these parameters and margin could be controlled with other CSS. (Haha sorry, I know you just added this for me).

**Comment by noxify** [comment]
Hi, 

Thanks again for reporting :)

We can change this, sure but I think removing both options could be a breaking change.

Translating the align value to a valid margin is not what I want - I assume that the users who are creating a site with Gridsome have some technical background ;) but you’re right, currently the user could create this cases.

Maybe removing `align` and for `margin` the default to `0 auto` should be ok - based on the current stats i‘m not sure how many sites are using the package. 


Is there any option to tell the user that there are breaking changes while running `npm update`?

But if you want, send a PR with the changes :)
Unfortunately I have no time until Sunday.

Thanks & regards
Marcus

**Comment by noxify** [comment]
Maybe there are some alternatives?
Like removed all inline css and allowing the definition of css classes which should be use in the HTML.
(And some fallback classes, e.g. `gridsome-embed-<providername>`

With this, the user has the flexibility to do what he/she want and it‘s not hardcoded in a template.

What do you think?
Any other ideas?

**Comment by missmatsuko** [comment]
> Translating the align value to a valid margin is not what I want - I assume that the users who are creating a site with Gridsome have some technical background ;) but you’re right, currently the user could create this cases.

I think it's ok not to validate that the user's put in a valid value for `margin` (so the devs could mess up the CSS), but `left` and `right` are documented as allowed values for `align`: https://github.com/noxify/gridsome-plugin-remark-embed#youtube

If these values are documented, they should produce valid CSS. So either remove them from the documentation or translate them to valid CSS?

> Maybe removing align and for margin the default to 0 auto should be ok - based on the current stats i‘m not sure how many sites are using the package.
>
> Is there any option to tell the user that there are breaking changes while running npm update?

I guess it's up to you! Could leave the code mainly as-is but remove `align` from documentation and warn when something is passed into it. Then could remove `align` and maybe `margin` in the next major version.

> Maybe there are some alternatives?
> Like removed all inline css and allowing the definition of css classes which should be use in the HTML.
> (And some fallback classes, e.g. gridsome-embed-<providername>
> 
> With this, the user has the flexibility to do what he/she want and it‘s not hardcoded in a template.

Could do. I think none of the other embeds have these options though, maybe it's not necessary at all?

**Comment by noxify** [comment]
For now, I removed the invalid values from the readme.
In one of the next releases I will replace the inline styles with css classes like `embed-youtube` or something like this.
