### ISSUE TITLE
Please add a class to Embeds so we can style them

### ISSUE THREAD

**Issue by RehanSaeed** [noxify/gridsome-plugin-remark-embed#35]
**Is your feature request related to a problem? Please describe.**
I want to style the position of embeds so the take negative left and right margin using CSS variables.

**Describe the solution you'd like**
Add `class="embed-youtube"` to the outer `div`.

**Comment by noxify** [comment]
Hi @RehanSaeed 

in the master branch, I did it already and added a wrapper div with a class name.

I haven't created a new version for this (not sure why).

If you need it ASAP, you could temporary create your own embed plugins.

**Comment by RehanSaeed** [comment]
I'll wait for a new published version. Thank you!

**Comment by noxify** [comment]
I will check it in the evening with the latest gridsome version to make sure it works as expected.
Then I will create a new version.

**Comment by noxify** [comment]
Short update: It seems I need some more time with testing.

The most of the providers are working fine but some need some additional attension.

I will continue tomorrow.

**Comment by noxify** [comment]
@RehanSaeed - new version is now published.
If something isn't working, feel free to create an issue :)

thanks!

regards,
marcus
