### ISSUE TITLE
Single YouTube Videos with Referenced Playlist Fail to Load

### ISSUE THREAD

**Issue by edm00se** [noxify/gridsome-plugin-remark-embed#38]
**Describe the bug**
Embedding a single video with a URL containing the playlist query param causes the embed to fail.

This was working previously; this change in behavior may have been introduced with commit 38eb029.

**To Reproduce**
1. Have a YouTube video link of a format `https://youtube.com/watch?v=<some-video-id>&list=<some-playlist-id>` in a source markdown file
2. Build and view the page

Example url in this format:
https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ

Generates an `iframe` (line breaks added for readability):
```html
<iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" 
src="https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ&list=RDdQw4w9WgXcQ"
allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
```

Which yields a non-working embed:
![generated yt embed with tailing "&list" in src is unusable](https://media.giphy.com/media/lS0vcqoLUYtDBSQzB6/source.gif)

**Expected behavior**
Video embed works. As the YouTube share/embed code doesn't seem to allow for including the playlist, dropping the playlist information should be acceptable.

**Additional context**
Looking [at the above example link with the old regex](https://regex101.com/r/R1GWl8/2) seems to work matching on just the video id. The [new regex from 38eb029 fails](https://regex101.com/r/ZCZZKA/2) and includes `&list=...` in the matched value.

I believe adjusting the regex to conditionally termiate at a first ampersand would correct this behavior. Unfortunately, my regex-fu is failing me in creating an updated regex pattern. If one is available, I'd be happy to open a PR for it.

Also, thank you for the hard work with this plugin! It's easy to use and configure, which is exactly what I was looking for.

**Comment by noxify** [comment]
Hi @edm00se 

thanks for reporting.

Yes, it seems that the mentioned commit is the reason for this issue.

I have created a playground with the updated urls which should work ( or not?! ):
https://regex101.com/r/kPbXGI/3

And here the example with the old regexp:
https://regex101.com/r/9Ef2it/2

---

It seems we have to merge them or create a alternative regexp which handles both cases.

Any ideas how we could solve this?

**Comment by edm00se** [comment]
I tried my hand at dong this a more "normal" JS way, since the regular expression approach seems to be getting a bit crazy. I first tried switching off a condition for using the old vs newer regex pattern, but eventually decided to try just parsing the url. This breaks with the approach used by the plugin here and incorporating it may be a bit more than a regex tweak, but at least it seems sane.

https://codesandbox.io/s/floral-dawn-bs67r?file=/index.ts

**Comment by noxify** [comment]
Thanks for the update and your time to find a solution.

I'm currently trying to solve it via RegEx.
I use https://www.debuggex.com/ to get it readable.

Glad that we have a holidays in germany tomorrow - it could be a long night :D

**Comment by noxify** [comment]
@edm00se i think I got it.

Definition:
https://www.debuggex.com/r/gm6rsrImNqXBS_9V

Example: 
https://regex101.com/r/99zR6X/1

But with this regex we have also to make some changes inside the `providers/Youtube.js`.


Changes are:
* Update the `isPlaylist` method and check also for `videoseries` and `playlist`
* Override the default `getEmbedId` method, because we have three groups 

What do you think?

Regards,
Marcus

**Comment by edm00se** [comment]
That looks pretty good to me. I'll have a go at creating a PR.

**Comment by edm00se** [comment]
I took a stab at it, it can be found in #39.

To be clear, I linked this on my local machine and successfully tested it in my repo that I noticed the issue in. I primarily have values like the one I described above, not every possible value format.

**Comment by noxify** [comment]
I will check it tomorrow

**Comment by noxify** [comment]
merged and released ✌️

**Comment by noxify** [comment]
Preview updated: https://gridsome-preview.ilovenox.now.sh/content/gridsome-content-test/youtube/

I have added the two missing examples.

**Comment by edm00se** [comment]
Excellent news.

**Comment by edm00se** [comment]
In case anyone comes across this after-the-fact and wonders why it isn't working, double-check that your YT url has the video id url param before the list param. `?v=XXXXX&list=YYYYY` as opposed to `?list=YYYY&v=XXXXX`.
