### ISSUE TITLE
SoundCloud ?height=x not working

### ISSUE THREAD

**Issue by Tragio** [noxify/gridsome-plugin-remark-embed#40]
**Describe the bug**
Using the following link `https://soundcloud.com/ean-golden/sets/love-and-shadow-an-ecstatic-dance-journey?height=300` to embed Soundcloud is not creating the height for 300px.

**To Reproduce**
My Gridsome config is simple, just with the enabled providers and the youtube with `nocookie: true` property.

Just put the link on a markdown file.

**Expected behavior**
It is expected to use the height in the link.

**Screenshots**
![Soundcloud Height Bug](https://user-images.githubusercontent.com/5109593/82992886-b0319780-9ff7-11ea-800a-3a923c6d9303.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version Latest

**Additional context**
Really thank you for this amazing plugin! ❤️

**Comment by noxify** [comment]
Hi @Kulcanhez 

thanks for reporting - i will check this.

**Comment by noxify** [comment]
Hey @Kulcanhez 

i can't reproduce your issue.

* Live Demo: https://gridsome-preview-rnagpio34.now.sh/content/gridsome-content-test/soundcloud/
* Test Data: https://github.com/noxify/gridsome-content-test/blob/master/soundcloud.md
* My gridsome setup: https://github.com/noxify/gridsome-preview

Did I missed something?

**Comment by noxify** [comment]
The generated html code is, for me, what I expect.

For `height=200`

![image](https://user-images.githubusercontent.com/521777/83117839-df1a3d00-a0cd-11ea-9dda-deb6d3316fd2.png)

For `height=400`

![image](https://user-images.githubusercontent.com/521777/83117958-04a74680-a0ce-11ea-9a95-dbd08bc46eac.png)

**Comment by Tragio** [comment]
Hello @noxify thank you for following this.

I was investigating and I noticed that I have an iframe `height: 100% `and other added by Bulma `height: auto;` only by disabling the two is that I have the specific height parameter.

![CSS Height iframe](https://user-images.githubusercontent.com/5109593/83118526-65328580-a0c6-11ea-9193-4ab832060b94.jpg)

**Comment by noxify** [comment]
maybe you can define something like

```
.soundcloud-embed iframe {
  height: auto;
}
```

to fix the problem?

**Comment by Tragio** [comment]
> maybe you can define something like
> 
> ```
> .soundcloud-embed iframe {
>   height: auto;
> }
> ```
> 
> to fix the problem?

@noxify hmmm it only fixes the problem if I uncheck all height iframe properties till I arrive the iframe[Attributes Style] `height: 300px;`.
`height: auto;` don't work and `height: 100%` doesn't work. So weird.

**Comment by noxify** [comment]
Hmm ... I’m not using bulma, so I can’t help you here - sorry. 

Maybe it could help if you create your own template for the SoundCloud provider.

Inside your template you have to extend the existing div with something like 
`style=“height: {{getValue options.height '300'}}px“`

This could help to keep the defined height.

Hope that helps.

Regards,
Marcus

**Comment by Tragio** [comment]
@noxify I fixed it by using `position: absolute` and `height: 300px`. It was the only way I found to easily fix it. Really thank you for your help and support. ❤️
