### ISSUE TITLE
Codepen doesn't work

### ISSUE THREAD

**Issue by D-Marc1** [noxify/gridsome-plugin-remark-embed#42]
**Describe the bug**
I get a blank box with a black outline when I use Codepen. I can see in the code that it has `<div class="codepen-embed">` wrapping the `p`. All the `data-` properties look correct as well.

**Screenshots**

<img width="756" alt="Screen Shot 2020-08-04 at 11 58 27 AM" src="https://user-images.githubusercontent.com/30007968/89316360-fb94a180-d649-11ea-8417-f65c593494da.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 84

**Comment by noxify** [comment]
Hi @D-Marc1,

thanks for reporting.

* Which codepen url are you using? ( here the used links from my example: https://github.com/noxify/gridsome-content-test/blob/master/codepen.md )
* Did you added the required assets for codepen? ( Here an example how I did it: https://github.com/noxify/gridsome-preview/blob/master/src/layouts/Default.vue#L56-L59 ) 


Thanks!

Regards,
Marcus

**Comment by D-Marc1** [comment]
@noxify Thanks for the reply. Great catch! Adding the following per your example you linked worked.

```js
const codepenScript = document.createElement('script');

codepenScript.async = true;

codepenScript.setAttribute('src', 'https://static.codepen.io/assets/embed/ei.js');

document.head.append(codepenScript);
```

Do you think this would be a good idea to add this directly to the plugin?

**Comment by noxify** [comment]
Hi @D-Marc1,

thanks for the feedback and glad that we could solve your problem :)

> Do you think this would be a good idea to add this directly to the plugin?

I was thinking about that, but decided to keep it in the responsibility of the user.
Also I'm not sure if this is the "right" way to add a script and also i don't want to be the "bad guy" if something went totally wrong after adding some magic into a existing layout.

**Comment by D-Marc1** [comment]
That's understandable. Thanks again for the help.

**Comment by D-Marc1** [comment]
@noxify Sorry for the double comment, don't mean to be annoying, but I just realized that an issue with passing the responsibility of adding the CodePen `<script>` tag to the user is that this will load the Codepen script regardless of if CodePen is even being used on the page. If this were added to the plugin, it would be possible to control when the Codepen script gets added.
