### ISSUE TITLE
Automatically import stylesheet for gist embeds

### ISSUE THREAD

**Issue by tnorthcutt** [noxify/gridsome-plugin-remark-embed#44]
Currently, the Gist provider requires that you manually fetch the stylesheet associated with the gist you want to embed.

However, we could instead fetch that, and insert it automatically.

Since that would be a breaking change, I propose that the Gist provider have a configuration option of `omitStylesheet` added, defaulting to `true`.

Then, if that is set to `false` in `gridsome.config.js`, we can fetch the stylesheet and append it to the inserted html.

If this would be a welcome addition, I'd be happy to provide a PR for it.

**Comment by tnorthcutt** [comment]
I just went ahead and made the PR. Hope it's useful!

**Comment by noxify** [comment]
@tnorthcutt merged and published a new version 1.3.0

**Comment by tnorthcutt** [comment]
Awesome!
