### ISSUE TITLE
Add Provider Instagram

### ISSUE THREAD

**Issue by noxify** [noxify/gridsome-plugin-remark-embed#5]
https://www.instagram.com/developer/embedding/#oembed

- [ ]  added provider class with regexp and options
- [ ]  added template
- [ ]  testing
- [ ] Readme updated

**Comment by davidnunez** [comment]
I'm interested in Instgram as a provider option. I noticed it was dropped in 5d335fc223d7385c02c129440629816ca2ae71bd - I'm ready to work out bugs and submit a PR, but curious if there is a bigger reason not to attempt?
